spring:
  application:
    name: "chatbot"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


openai:
  api:
    key: ${OPENAI_API_KEY}
    baseUrl: ${OPENAI_API_URL}
    embedding: "/v1/embeddings"
    chat: "/v1/chat/completions"
google:
  api:
    key: ${GOOGLE_API_KEY}
    baseUrl: ${GOOGLE_API_URL}
    embedding: "/v1beta/models/gemini-embedding-001:embedContent"
    chat: "/v1beta/models/gemini-2.0-flash:generateContent"

embedding:
  provider: google  # default provider, can switch to google/other
chat:
  provider: google


